name: Deploy CF Workflows
on: 
  push:
    paths:
      - server/workflows/**
      - server/tools/**
      - .github/workflows/cf-workflows.yml

jobs:
  deploy:
    name: "Deploy to Cloudflare"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Prepare Tools Runtime
        run: pnpm postinstall

      - name: Build & Deploy Each Workflow to Cloudflare
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          cd server/workflows
          for dir in $(find . -mindepth 1 -maxdepth 1 -type d); do cd "$dir"; npx wrangler deploy; pwd; cd ..; done
          
